travis:
  secure:
    BINSTAR_TOKEN: ZFySJkISVMR92kAciqckWLUoAO2gT0JEX+L6U9/9uxe7janhgDGzy/KmzwEiRWjgLaZweWMHPe4fKB9JU2R5Bu/YnZo5NUDG+O3yYqS8/bgro5Wb+WY+0sLazRg1SefClaziiByw6+j2OVBcZziNI5KLjRuxPvB8ifDEaZjEqNpf4UM9o+sx8cS7OFIABvpIp34IpjyWQIA5PmlWPraoL3gkwlUO98R74mfikK9WaQ0luHhpFBb2vBS8NijhwWaFg8vmX08nxZR5aEF0EzoZtIP4mdzgDrK2BdHSBD9ToMMTuSup5MQ422rqQONe/xBvMES5t0BzZwf0eDRMWzgc2Z+9YchVwDjHSkkTh7D4x+ijJg16Ss2m14OXNIyMMMrPasTbO96o8c4Tug2JMPQwQUIvv06EPAmeNx6tUZoQtP9aR5iNNNGjFyjW83QcoxWPYwvyYoAqIauT17KKnkae8Ll3nj5xamGSt2BdtfgunbASVpBCqIEp+npMq3eDuDFuTd++eGjUJnbgBBcO5J/UYUBu4bFAofETazm/LN6GGc4KemPciKAj6ahZzD15gwNvYGKUmyJF84qeFX8lRVkOYgDtj+PVVmf8nObAgI12nfHykvcleOUd1rgWudNQTirEQZ5v/hF530how/2/rTHIeppzyAcBjMZ+Ng3MCNqMb+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
